import * as Print from 'expo-print'
import * as Sharing from 'expo-sharing'
import { Alert } from 'react-native'

const BUILDING_UPI_NAME = 'Madhuvan Apartment'

// Generates and shares a PDF receipt for a single due row.
// `due` needs: id, total, month, paid_at
// `profile` needs: flat_number, full_name
export async function generateReceipt(due, profile) {
  const paidDate = due.paid_at
    ? new Date(due.paid_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    : '—'
  const receiptNumber = due.id.slice(0, 8).toUpperCase()

  const html = `
    <html>
      <body style="font-family: Helvetica; padding: 32px; color: #13231F;">
        <h1 style="font-size: 20px; margin-bottom: 4px;">${BUILDING_UPI_NAME}</h1>
        <p style="color: #7A7267; font-size: 12px; margin-top: 0;">Maintenance Payment Receipt</p>
        <hr style="border: none; border-top: 1px solid #E3D9C2; margin: 20px 0;" />
        <table style="width: 100%; font-size: 14px;">
          <tr><td style="padding: 6px 0; color: #7A7267;">Receipt No.</td><td style="text-align: right;">${receiptNumber}</td></tr>
          <tr><td style="padding: 6px 0; color: #7A7267;">Flat</td><td style="text-align: right;">${profile.flat_number}</td></tr>
          <tr><td style="padding: 6px 0; color: #7A7267;">Resident</td><td style="text-align: right;">${profile.full_name}</td></tr>
          <tr><td style="padding: 6px 0; color: #7A7267;">Month</td><td style="text-align: right;">${new Date(due.month).toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}</td></tr>
          <tr><td style="padding: 6px 0; color: #7A7267;">Date paid</td><td style="text-align: right;">${paidDate}</td></tr>
        </table>
        <hr style="border: none; border-top: 1px solid #E3D9C2; margin: 20px 0;" />
        <table style="width: 100%; font-size: 16px; font-weight: bold;">
          <tr><td>Total paid</td><td style="text-align: right;">₹${due.total}</td></tr>
        </table>
        <p style="color: #7A7267; font-size: 11px; margin-top: 32px;">Generated by Club — this is a system-generated receipt.</p>
      </body>
    </html>
  `

  try {
    const { uri } = await Print.printToFileAsync({ html })
    await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' })
  } catch (err) {
    Alert.alert('Could not generate receipt', err.message)
  }
}
