import { useState } from 'react'
import { View, Text, TextInput, TouchableOpacity, StyleSheet, ScrollView, Linking, Alert } from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { supabase } from '../lib/supabase'
import { useAuth } from '../lib/AuthContext'
import { colors, spacing, radius, type, VENDOR_CATEGORIES } from '../lib/theme'
import Card from '../components/ui/Card'
import Button from '../components/ui/Button'
import Badge from '../components/ui/Badge'

// Simple date chips instead of a full date picker — avoids pulling in
// @react-native-community/datetimepicker as a new native dependency for MVP.
function nextNDays(n) {
  const days = []
  for (let i = 0; i < n; i++) {
    const d = new Date()
    d.setDate(d.getDate() + i)
    days.push(d)
  }
  return days
}

// slot_time in your table is a single timestamp, not separate date+slot
// fields — so each time slot maps to an hour we combine with the picked date.
const TIME_SLOTS = [
  { label: 'Morning', hour: 9 },
  { label: 'Afternoon', hour: 13 },
  { label: 'Evening', hour: 17 },
]

export default function VendorDetailScreen({ route, navigation }) {
  const { vendor } = route.params
  const { profile } = useAuth()

  const [selectedDate, setSelectedDate] = useState(null)
  const [selectedSlot, setSelectedSlot] = useState(null)
  const [note, setNote] = useState('')
  const [submitting, setSubmitting] = useState(false)

  const dateOptions = nextNDays(5)

  function callVendor() {
    if (!vendor.phone) {
      Alert.alert('No phone number', 'This vendor has no phone number on file yet.')
      return
    }
    Linking.openURL(`tel:${vendor.phone}`)
  }

  async function submitBooking() {
    if (!selectedDate || !selectedSlot) {
      Alert.alert('Pick a date and time', 'Choose when you\'d like the vendor to come by.')
      return
    }
    setSubmitting(true)

    const slotTime = new Date(selectedDate)
    slotTime.setHours(selectedSlot.hour, 0, 0, 0)

    // id and booking_id are both auto-generated by the table — we don't set
    // either here.
    const { error } = await supabase.from('vendor_bookings').insert({
      vendor_id: vendor.id,
      resident_id: profile.id,
      building_id: profile.building_id,
      flat_number: profile.flat_number,
      slot_time: slotTime.toISOString(),
      note: note.trim() || null,
      status: 'requested',
    })

    setSubmitting(false)
    if (error) {
      Alert.alert('Could not submit booking', error.message)
      return
    }
    Alert.alert('Request sent', `${vendor.name} will be notified. You can track this in My Bookings.`, [
      { text: 'OK', onPress: () => navigation.goBack() },
    ])
  }

  const categoryLabel = VENDOR_CATEGORIES.find(c => c.key === vendor.category)?.label || vendor.category

  return (
    <ScrollView style={styles.page} contentContainerStyle={{ padding: spacing.xl }}>
      <Card>
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.md }}>
          <View style={styles.icon}>
            <Ionicons name="construct-outline" size={24} color={colors.accent} />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={type.h1}>{vendor.name}</Text>
            <Badge label={categoryLabel} tone="cove" />
          </View>
        </View>

        <View style={styles.statsRow}>
          <Text style={type.bodyMuted}>★ {vendor.rating?.toFixed(1) || '—'}</Text>
          <Text style={type.bodyMuted}>{vendor.jobs_completed || 0} jobs completed</Text>
        </View>

        <Button label="Call vendor" onPress={callVendor} variant="outline" style={{ marginTop: spacing.md }} />
      </Card>

      <Card>
        <Text style={type.eyebrow}>Book this vendor</Text>

        <Text style={styles.label}>Pick a date</Text>
        <View style={styles.chipRow}>
          {dateOptions.map((d, i) => {
            const active = selectedDate?.toDateString() === d.toDateString()
            const label = i === 0 ? 'Today' : i === 1 ? 'Tomorrow' : d.toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric' })
            return (
              <TouchableOpacity
                key={i}
                style={[styles.chip, active && styles.chipActive]}
                onPress={() => setSelectedDate(d)}
              >
                <Text style={[styles.chipText, active && styles.chipTextActive]}>{label}</Text>
              </TouchableOpacity>
            )
          })}
        </View>

        <Text style={[styles.label, { marginTop: spacing.md }]}>Pick a time</Text>
        <View style={styles.chipRow}>
          {TIME_SLOTS.map(slot => {
            const active = selectedSlot?.label === slot.label
            return (
              <TouchableOpacity
                key={slot.label}
                style={[styles.chip, active && styles.chipActive]}
                onPress={() => setSelectedSlot(slot)}
              >
                <Text style={[styles.chipText, active && styles.chipTextActive]}>{slot.label}</Text>
              </TouchableOpacity>
            )
          })}
        </View>

        <Text style={[styles.label, { marginTop: spacing.md }]}>Note (optional)</Text>
        <TextInput
          style={styles.textArea}
          placeholder="e.g. Kitchen tap leaking, please bring washer"
          placeholderTextColor={colors.textFaint}
          value={note}
          onChangeText={setNote}
          multiline
        />

        <Button
          label={submitting ? 'Sending request…' : 'Send booking request'}
          onPress={submitBooking}
          loading={submitting}
          style={{ alignSelf: 'stretch', marginTop: spacing.md }}
        />
      </Card>
    </ScrollView>
  )
}

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.bg },
  icon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statsRow: { flexDirection: 'row', gap: spacing.lg, marginTop: spacing.md },
  label: { ...type.bodyMuted, marginBottom: spacing.sm },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  chip: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingVertical: spacing.sm, paddingHorizontal: spacing.md, backgroundColor: colors.surface },
  chipActive: { backgroundColor: colors.accent, borderColor: colors.accent },
  chipText: { fontSize: 12.5, fontWeight: '600', color: colors.text },
  chipTextActive: { color: colors.text },
  textArea: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md, fontSize: 13, minHeight: 70, textAlignVertical: 'top', color: colors.text, backgroundColor: colors.surface },
})
